/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbc_mhs_service_GUI.program;
import jdbc_mhs_service_GUI.model.Mahasiswa;
import jdbc_mhs_service_GUI.service.MysqlMahasiswaService;
/**
 *
 * @author Sulthon
 */
import javax.swing.*;
import java.util.*;
public class JFrameUtama extends javax.swing.JFrame {
    DefaultListModel<String> dlmNama; 
    DefaultListModel<String> dlmId;     
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameUtama.class.getName());

    /**
     * Creates new form JFrameUtama
     */
    public JFrameUtama() {
        initComponents();
        this.dlmNama = new DefaultListModel<>();
        this.dlmId = new DefaultListModel<>();
        this.listNama.setModel(dlmNama);
        this.listId.setModel(dlmId);
        listId.addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            int index = listId.getSelectedIndex();
            if (index >= 0) {
                // Isi textfield ID dan Nama di bagian Edit
                txtIdEdit.setText(dlmId.getElementAt(index));
                txtNamaEdit.setText(dlmNama.getElementAt(index));
                
                // Isi textfield ID dan Nama di bagian Hapus
                txtIdHapus.setText(dlmId.getElementAt(index));
                txtNamaHapus.setText(dlmNama.getElementAt(index));
            }
        }
        });
    }
    
    private void addItem(int id, String namaItem){
        dlmNama.addElement(namaItem);
        dlmId.addElement(String.valueOf(id));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelId = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelKelola = new javax.swing.JLabel();
        btnAmbilSemuaData = new javax.swing.JButton();
        labelInputNama = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listNama = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listId = new javax.swing.JList<>();
        btnTambahkan = new javax.swing.JButton();
        txtIdEdit = new javax.swing.JTextField();
        txtNamaEdit = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        txtIdHapus = new javax.swing.JTextField();
        txtNamaHapus = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        btnResetIndeks = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        labelIndexReset = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        labelId.setBackground(new java.awt.Color(255, 255, 255));
        labelId.setText("ID");

        labelNama.setText("NAMA");

        labelKelola.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelKelola.setText("Kelola Data Mahasiswa");

        btnAmbilSemuaData.setBackground(new java.awt.Color(214, 217, 224));
        btnAmbilSemuaData.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnAmbilSemuaData.setForeground(new java.awt.Color(30, 30, 30));
        btnAmbilSemuaData.setText("Ambil Semua Data");
        btnAmbilSemuaData.addActionListener(this::btnAmbilSemuaDataActionPerformed);

        labelInputNama.setText("nama:");

        txtNama.addActionListener(this::txtNamaActionPerformed);

        listNama.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listNama);

        listId.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listId);

        btnTambahkan.setBackground(new java.awt.Color(214, 217, 224));
        btnTambahkan.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnTambahkan.setForeground(new java.awt.Color(30, 30, 30));
        btnTambahkan.setText("Tambahkan");
        btnTambahkan.addActionListener(this::btnTambahkanActionPerformed);

        txtIdEdit.addActionListener(this::txtIdEditActionPerformed);

        btnEdit.setBackground(new java.awt.Color(214, 217, 224));
        btnEdit.setForeground(new java.awt.Color(30, 30, 30));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnHapus.setBackground(new java.awt.Color(214, 217, 224));
        btnHapus.setForeground(new java.awt.Color(30, 30, 30));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnResetIndeks.setBackground(new java.awt.Color(214, 217, 224));
        btnResetIndeks.setForeground(new java.awt.Color(30, 30, 30));
        btnResetIndeks.setText("Reset Indeks");
        btnResetIndeks.addActionListener(this::btnResetIndeksActionPerformed);

        labelIndexReset.setText("Index di reset ke 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelInputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAmbilSemuaData)
                        .addComponent(btnTambahkan)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtIdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNamaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEdit))
                        .addComponent(txtNama)
                        .addComponent(labelKelola))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIdHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNamaHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnResetIndeks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelIndexReset))))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNama)
                            .addComponent(labelKelola))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnAmbilSemuaData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelInputNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTambahkan)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapus))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnResetIndeks)
                            .addComponent(jLabel1)
                            .addComponent(labelIndexReset))))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnAmbilSemuaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmbilSemuaDataActionPerformed
        // TODO add your handling code here:
        dlmId.clear();
        dlmNama.clear();
        
        MysqlMahasiswaService service = new MysqlMahasiswaService();
        List<Mahasiswa> list = service.getAll();
        
        for(Mahasiswa m : list){
            addItem(m.getId(), m.getNama());
        }
    }//GEN-LAST:event_btnAmbilSemuaDataActionPerformed

    private void btnTambahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahkanActionPerformed
        // TODO add your handling code here:
        String nama = txtNama.getText().trim();
        MysqlMahasiswaService service = new MysqlMahasiswaService();
        Mahasiswa mhs = service.makeMhsObject();
        mhs.setNama(nama);
        service.add(mhs);
        dlmId.clear();
        dlmNama.clear();
        List<Mahasiswa> list = service.getAll();
        for (Mahasiswa m : list) {
            addItem(m.getId(), m.getNama());
        }
        txtNama.setText("");
    }//GEN-LAST:event_btnTambahkanActionPerformed

    private void txtIdEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEditActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int index = listId.getSelectedIndex();
        String namaBaru = txtNamaEdit.getText().trim();
        int id = Integer.parseInt(dlmId.getElementAt(index));
        MysqlMahasiswaService service = new MysqlMahasiswaService();
        Mahasiswa mhs = service.makeMhsObject();
        mhs.setId(id);
        mhs.setNama(namaBaru);
        service.update(mhs);
        dlmNama.setElementAt(namaBaru, index);
        txtIdEdit.setText("");
        txtNamaEdit.setText("");
                     
        txtIdHapus.setText("");
        txtNamaHapus.setText("");
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int index = listId.getSelectedIndex();
        int id = Integer.parseInt(dlmId.getElementAt(index));
        MysqlMahasiswaService service = new MysqlMahasiswaService();
        service.delete(id);
        dlmNama.removeElementAt(index);
        dlmId.removeElementAt(index);
        txtIdEdit.setText("");
        txtNamaEdit.setText("");
                
                
        txtIdHapus.setText("");
        txtNamaHapus.setText("");
                
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetIndeksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetIndeksActionPerformed
        // TODO add your handling code here:
        MysqlMahasiswaService service = new MysqlMahasiswaService();
       
        if(service.isEmpty()) {
            service.indexReset();
            labelIndexReset.setText("Index direset ke 1");
        }else {
            JOptionPane.showMessageDialog(this,
            "Tabel tidak kosong!\nHapus semua data dulu.",
            "Peringatan", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_btnResetIndeksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmbilSemuaData;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JToggleButton btnResetIndeks;
    private javax.swing.JButton btnTambahkan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelIndexReset;
    private javax.swing.JLabel labelInputNama;
    private javax.swing.JLabel labelKelola;
    private javax.swing.JLabel labelNama;
    private javax.swing.JList<String> listId;
    private javax.swing.JList<String> listNama;
    private javax.swing.JTextField txtIdEdit;
    private javax.swing.JTextField txtIdHapus;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaEdit;
    private javax.swing.JTextField txtNamaHapus;
    // End of variables declaration//GEN-END:variables
}
